# Generated by Django 2.1.5 on 2022-07-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220727_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discout',
            new_name='discount',
        ),
    ]
